# Generated by Django 5.0.1 on 2024-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datas',
            name='Address',
        ),
        migrations.AlterField(
            model_name='datas',
            name='Contact',
            field=models.CharField(default='', max_length=20),
        ),
    ]
